version: '3.8'
services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    environment:
      - REPO=florianvsteen/lightweightchart-agent
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    deploy:
      mode: replicated
      replicas: 4
      #resources:
      #  limits:
      #    cpus: '0.5'
      #    memory: 512M
      #  reservations:
      #    cpus: '0.4'
      #    memory: 256M
