version: '3.8'
services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    environment:
      - REPO=florianvsteen/lightweightchart-agent
      - REG_TOKEN=BNDGSDEPUUK5FMEGKJCXHR3J36RVM
      - NAME=FLOWNET-GH-RUNNER
    deploy:
      mode: replicated
      replicas: 1
      #resources:
      #  limits:
      #    cpus: '0.5'
      #    memory: 512M
      #  reservations:
      #    cpus: '0.4'
      #    memory: 256M
